config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint_fix
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/micheleartini/dnet-oai-server:
      branch: main
      repo: https://github.com/micheleartini/dnet-oai-server.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/micheleartini/dnet-oai-server git:
        commands:
        - /usr/bin/env sh .sqa/script.porcelain_frugal_kangaroo.sh
        container: qc.acc_turquoise_resilient_stork
  QC.Doc:
    repos:
      github.com/micheleartini/dnet-oai-server find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.fandango_enthusiastic_heron.sh
        container: qc.doc_rose_agile_clownfish
      github.com/micheleartini/dnet-oai-server git:
        commands:
        - /usr/bin/env sh .sqa/script.wheat_happy_fox.sh
        container: qc.doc_raspberry_tactful_capybara
      github.com/micheleartini/dnet-oai-server markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.jade_perceptive_sloth.sh
        container: qc.doc_apricot_observant_ibis
  QC.Lic:
    repos:
      github.com/micheleartini/dnet-oai-server licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cherry_supportive_orca.sh
        container: qc.lic_orchid_scrappy_wasp
  QC.Sty:
    repos:
      github.com/micheleartini/dnet-oai-server checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.cayenne_intuitive_cormorant.sh
        container: qc.sty_khaki_hopeful_kookaburra
      github.com/micheleartini/dnet-oai-server jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.lilac_imaginative_nymph.sh
        container: qc.sty_obsidian_diplomatic_tortoise
  QC.Ver:
    repos:
      github.com/micheleartini/dnet-oai-server get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.coral_alert_parrot.sh
        container: qc.ver_forest_smart_unicorn
timeout: 5400
